#ifndef _PARSER_PARSER_H_
#define _PARSER_PARSER_H_

typedef enum parser_state
{
	PARSER_NEW_MESSAGE = 0,
	PARSER_WAIT_START,
	PARSER_WAIT_HEADER,
	PARSER_WAIT_LENGTH,
	PARSER_WAIT_MSG_ID,
	PARSER_WAIT_PAYLOAD,
	PARSER_WAIT_CRC_L,
	PARSER_WAIT_CRC_H,
	PARSER_ERROR,
} parser_state_t;

#endif /** !_PARSER_PARSER_H_ */